name: online_shop
description: Online Shop With redis
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-172.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  redis: ^2.0.0
  # Lottie
  lottie: any
  # File Picker
  file_picker: ^4.0.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.8
  shamsi_date: ^0.16.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/lottie/.
  fonts:
    - family: IRANSans
      fonts:
        - asset: fonts/IRANSansMobile.ttf